spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: null
    timeout: 60000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1
        max-active: -1

